"""add_exit_policy_to_backtest

Revision ID: 3af5a19a14c9
Revises: 86894cd676cb
Create Date: 2026-04-17 23:47:53.623881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af5a19a14c9'
down_revision: Union[str, None] = '86894cd676cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('exit_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'exit_policy')
    # ### end Alembic commands ###
