"""initial_schema

Revision ID: e47ea07f0ffe
Revises: 
Create Date: 2026-04-17 16:58:15.176449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e47ea07f0ffe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('symbols', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('timeframes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('run_frequency', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_symbols', sa.Integer(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_events', 'system_events', ['event_type', 'created_at'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('symbols', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annualized_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('avg_hold_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('llm_evaluation', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ohlcv_bars',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('bar_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'bar_time')
    )
    op.create_index('idx_bars', 'ohlcv_bars', ['instrument_id', 'timeframe', 'bar_time'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['underlying'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('idx_options_underlying', 'options', ['underlying', 'expiry', 'strike'], unique=False)
    op.create_table('backtest_equity_curve',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('backtest_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bt_equity', 'backtest_equity_curve', ['backtest_id', 'ts'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('backtest_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('hold_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('entry_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exit_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bt_trades', 'backtest_trades', ['backtest_id', 'entry_time'], unique=False)
    op.create_table('option_chain_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('bid', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ask', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('iv', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('delta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('theta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('vega', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chain', 'option_chain_snapshots', ['option_id', 'snapshot_time'], unique=False)
    op.create_table('trade_signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('signal_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('(stock_id IS NOT NULL AND option_id IS NULL) OR (stock_id IS NULL AND option_id IS NOT NULL)', name='ck_signal_instrument'),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_status', 'trade_signals', ['status', 'created_at'], unique=False)
    op.create_index('idx_signals_strategy', 'trade_signals', ['strategy_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signals_strategy', table_name='trade_signals')
    op.drop_index('idx_signals_status', table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index('idx_chain', table_name='option_chain_snapshots')
    op.drop_table('option_chain_snapshots')
    op.drop_index('idx_bt_trades', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('idx_bt_equity', table_name='backtest_equity_curve')
    op.drop_table('backtest_equity_curve')
    op.drop_index('idx_options_underlying', table_name='options')
    op.drop_table('options')
    op.drop_index('idx_bars', table_name='ohlcv_bars')
    op.drop_table('ohlcv_bars')
    op.drop_table('backtests')
    op.drop_index('idx_system_events', table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('strategies')
    op.drop_table('instruments')
    # ### end Alembic commands ###
